---
- hosts: all
  become: true
  tasks:
   - name: check connectivity
     ping:
   - name: Add PPA repoistry
     apt_repository: repo={{item}}
     with_items:
       - 'ppa:ondrej/php'
       - 'ppa:ondrej/mysql-5.6'
   - name: Update the Apt Cache
     apt: update_cache=yes cache_valid_time=3600
   - name: Install Php
     apt: name={{item}} state=installed 
     with_items:
       - php
       - php-fpm
       - php-mysql
       - php-xml
   - name: Remove apache2
     apt: name=apache2 state=removed
   - name: MySQL install
     apt: name={{item}} state=installed
     with_items:
       - mysql-server-5.6
       - python-mysqldb
   - name: Generate mysql root password
     command: openssl rand -hex 7 creates=/root/.my.cnf
     register: mysql_new_root_pass
   - debug: msg=" new root password is {{mysql_new_root_pass.stdout}} "
     when: mysql_new_root_pass.changed
   - debug: msg=" No Change in password "
     when: not mysql_new_root_pass.changed
   - name: Remove anonymous Users
     mysql_user: name="" state=absent
     when: mysql_new_root_pass.changed
   - name: Remove test database
     mysql_db: name=test state=absent
     when: mysql_new_root_pass.changed
   - name: Update root password
     mysql_user: name=root host={{item}} password={{mysql_new_root_pass.stdout}}
     with_items:
      - "{{ansible_hostname}}"
      - 127.0.0.1
      - ::1
      - localhost
     when: mysql_new_root_pass.changed
   - name: Create SQL my.cnf
     template: src=templates/mysql/my.cnf dest=/root/.my.cnf
     when: mysql_new_root_pass.changed
   - name: Nginx Install
     apt: name=nginx state=installed
   - name: Start nginx Service
     service: name=nginx state=running
   - name: Create Nginx configuration
     template: src=templates/nginx/default dest=/etc/nginx/sites-available/default
     notify: restart nginx
   - name: Copy Wordpress zip to temp
     copy: src=files/wordpress.zip dest=/tmp/wordpress.zip
   - name: Install Unzip Program
     apt: name={{item}} state=installed 
     with_items:
       - unzip
   - name: Unzip Wordpress
     unarchive: src=/tmp/wordpress.zip dest=/tmp copy=no creates=/tmp/wordpress/wp-settings.php
   - name: Create Project Folder
     file: dest=/var/www/book.example.com state=directory
   - name: Copy Wordpress files
     command: cp -a /tmp/wordpress/. /var/www/book.example.com creates=/var/www/book.example.com/wp-settings.php
   - name: Create WordPress MySQL database
     mysql_db: name=wordpress state=present
   - name: Creates WordPress MySQL user
     mysql_user: name=wordpress host=localhost password=ansible priv=wordpress.*:ALL
   - name: Creates wp-config
     template: src=templates/wordpress/wp-config.php dest=/var/www/book.example.com/wp-config.php
   - name: Checking if Wordpress DB exists ..
     command: mysql -u root wordpress -e 'SELECT ID FROM wordpress.wp_users LIMIT 1;'
     register: db_exist
     ignore_errors: true
     changed_when: false
   - name: Copy Wordpress DB
     copy: src=files/wp-database.sql dest=/tmp/wp-database.sql
     when: db_exist.rc > 0
   - name: Import Wordpress DB
     mysql_db: target=/tmp/wp-database.sql state=import name=wordpress
     when: db_exist.rc > 0
  handlers:
   - name: restart nginx
     service: name=nginx state=restarted
